// Copyright (c) 2009-2010 Satoshi Nakamoto
// Copyright (c) 2010-2018 The Bitcoin developers
// Original code was distributed under the MIT software license.
// Copyright (c) 2014-2018 TEDLab Sciences Ltd
// Gamechain code distributed under the GPLv3 license, see COPYING file.

#ifndef GAMECHAINVERSION_H
#define	GAMECHAINVERSION_H

#define GAMECHAIN_VERSION_MAJOR     1
#define GAMECHAIN_VERSION_MINOR     0
#define GAMECHAIN_VERSION_REVISION  0
#define GAMECHAIN_VERSION_STAGE     2
#define GAMECHAIN_VERSION_BUILD     2

#define GAMECHAIN_PROTOCOL_VERSION 10008
#define GAMECHAIN_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define GAMECHAIN_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define GAMECHAIN_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define GAMECHAIN_BUILD_DESC "1.0 beta 2"
#define GAMECHAIN_BUILD_DESC_NUMERIC 10000202


#ifndef GAMECHAIN_BUILD_DESC
#ifdef BUILD_SUFFIX
#define GAMECHAIN_BUILD_DESC GAMECHAIN_BUILD_DESC_WITH_SUFFIX(GAMECHAIN_VERSION_MAJOR, GAMECHAIN_VERSION_MINOR, GAMECHAIN_VERSION_REVISION, GAMECHAIN_VERSION_BUILD, BUILD_SUFFIX)
#else
#define GAMECHAIN_BUILD_DESC GAMECHAIN_BUILD_DESC_FROM_UNKNOWN(GAMECHAIN_VERSION_MAJOR, GAMECHAIN_VERSION_MINOR, GAMECHAIN_VERSION_REVISION, GAMECHAIN_VERSION_BUILD)
#endif
#endif

#define GAMECHAIN_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef GAMECHAIN_FULL_VERSION
#define GAMECHAIN_FULL_VERSION GAMECHAIN_FULL_DESC(GAMECHAIN_BUILD_DESC, GAMECHAIN_PROTOCOL_VERSION)
#endif


#define GAMECHAIN_VERSION_CODE_PROTOCOL_THIS              0
#define GAMECHAIN_VERSION_CODE_PROTOCOL_MIN               1
#define GAMECHAIN_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define GAMECHAIN_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define GAMECHAIN_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define GAMECHAIN_VERSION_CODE_BUILD                     16
#define GAMECHAIN_VERSION_CODE_MIN_VALID               1000

#endif	/* GAMECHAINVERSION_H */

